table ProductCostHistory
	lineageTag: 4317113d-a03b-49cf-94c5-732865caf480

	column Year
		dataType: int64
		formatString: 0
		lineageTag: f57509fb-96a3-4c53-a715-3290d1fc06e0
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: 0
		lineageTag: 17bc5454-65c5-4db9-b5cd-eddc659d793b
		summarizeBy: sum
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column CountryCode
		dataType: string
		lineageTag: 280177cf-3d87-4ee6-a7d0-79461801789d
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 01cf252d-1a63-4720-8d61-b58565981f6f
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: f450c01b-8a11-4429-827f-bed4ae60405e
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ProductCostHistory = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\work\projects\data x projects\New folder\ROW_DATA.xlsx"), null, true),
				    ProductCostHistory_Table = Source{[Item="ProductCostHistory",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(ProductCostHistory_Table,{{"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"CountryCode", type text}, {"ProductKey", Int64.Type}, {"UnitCost", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

